# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69ccaa6163995ba6e67b4dc54ee9da0bd57f54a889c5d08322cfd6eba95637a9248bc469dc3f4c1bc66e2e9f284823b61fcf6fd3ade09a31f54f794026ed53e6

test:
  secret_key_base: 994eaba149d81db6b2f72d1fbb8667187d089ebaf01598b555c7cbfd6987bea1b5d74589f69fe3d38f33bc65c8302c6d579e3ca0e20a32599ceacb0d8844c1da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
